# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Beast
last_update: "Site last built: "
description: > # this means to ignore newlines until "baseurl:"
  In the middle :clock12: of the night The Beast lurks out there in cyberspace
  wielding his XSL tipped lightsaber that was forged with a super hardened blend of PHP, Ruby,
  Javascript and Python.  For The Beast had been <a href="https://www.google.com.au/search?q=kung+fu+rigorous+training+images&espv=2&biw=1538&bih=1503&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwjc7JfYjvXPAhXJmpQKHeC8BncQsAQIGg#tbm=isch&q=kung+fu+hard+training+images" target="_blank">rigourously trained</a>
  in childhood on the <a href="https://en.wikipedia.org/wiki/Atari" target="_blank">Atari</a>
  and <a href="https://www.google.com.au/search?q=hard+strength+conditioning+images&espv=2&biw=1538&bih=1503&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwix3LGAj_XPAhWCOJQKHWCtD3kQsAQIGg#tbm=isch&q=hard+strength+training+images" target="_blank">conditioned</a>
  on the likes of the <a href="https://en.wikipedia.org/wiki/Commodore_VIC-20" target="_blank">VIC-20</a>
  and the <a href="https://en.wikipedia.org/wiki/IBM_Personal_Computer_XT" target="_blank">XT</a>.
  Decades now have passed :warning::warning::warning:
  Enter The Beast :boom::boom::boom::exclamation::exclamation:
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jbampton.github.io" # the base hostname & protocol for your site
twitter_username: johnbampton
github_username:  jbampton

# Build settings
markdown: kramdown
gems:
  - jemoji
