# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Beast
last_update: "Site last built: "
description: > # this means to ignore newlines until "baseurl:"
  In the middle of the night The Beast lurks out there in cyberspace
  wielding his lightsaber that was forged with a super hardened blend of PHP and Ruby.
  For The Beast had been rigourously trained in childhood on the Atari and conditioned
  on the likes of the VIC-20 and the XT. Decades now have passed....Enter The Beast..!?!?!!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jbampton.github.io" # the base hostname & protocol for your site
twitter_username: johnbampton
github_username:  jbampton

# Build settings
markdown: kramdown
