# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chariots of Fire
description: > # this means to ignore newlines until "baseurl:"
  In the middle of the night Beast lurks out there in cyber space
  wielding his lightsaber that was forged with a blend of PHP and Ruby.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jbampton.github.io" # the base hostname & protocol for your site
twitter_username: johnbampton
github_username:  jbampton

# Build settings
markdown: kramdown
